plugins {
    id 'com.android.application'
}

def getGitCommit() {
    try {
        return "git describe --always".execute(null, project.rootDir).text.trim()
    } catch (Exception e) {
        return "unknown"
    }
}

android {
    namespace 'com.runbeat.pro'
    compileSdk 34
    buildFeatures { buildConfig true }
    lint { checkReleaseBuilds = false }

    defaultConfig {
        applicationId "com.runbeat.pro"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
        buildConfigField "String", "BUILD_TIME", "\"${new Date().format('yyyy-MM-dd HH:mm:ss')}\""
        buildConfigField "String", "GIT_COMMIT", "\"${getGitCommit()}\""
        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    android.applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = "RunBeatPro-v${defaultConfig.versionName}-${getGitCommit()}-${variant.buildType.name}.apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    ndkVersion = '25.2.9519653'
    externalNativeBuild {
        cmake {
            path "../../cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    constraints {
        implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22') {
            because 'Force Kotlin stdlib version to avoid duplicates'
        }
        implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22') {
            because 'Force Kotlin stdlib version to avoid duplicates'
        }
    }
}
